- name: Install useful desktop tools (dnf)
  become: yes
  dnf: name={{ item }} state=present
  with_items: "{{ desktop.tools }}"
  when: ansible_pkg_mgr == "dnf"
  tags:
    - packages
    - network

- name: Install useful desktop tools (yum)
  become: yes
  yum: name={{ item }} state=present
  with_items: "{{ desktop.tools }}"
  when: ansible_pkg_mgr == "yum"
  tags:
    - packages
    - network

