---
ansible_connection: local

dotfiles:
  dependencies:
    - bash
    - bash-completion
    - ack
    - grep
    - links
    - tmux
    - screen
    - git
    - mc
    - sysstat
    - telnet
    - mutt
    - htop

vim:
  folders:
    - .vim
    - .vim/autoload
    - .vim/bundle
    - .vim/sessions
    - .vim/undodir
  dependencies:
    - vim-enhanced
    - ctags
    - git
    - ack
  plugins:
    - https://github.com/airblade/vim-gitgutter.git
    - https://github.com/ctrlpvim/ctrlp.vim
    - https://github.com/docunext/closetag.vim.git
    - https://github.com/editorconfig/editorconfig-vim.git
    - https://github.com/ervandew/supertab.git
    - https://github.com/flazz/vim-colorschemes.git
    - https://github.com/majutsushi/tagbar.git
    - https://github.com/MarcWeber/vim-addon-mw-utils.git
    - https://github.com/mattn/gist-vim.git
    - https://github.com/mattn/webapi-vim.git
    - https://github.com/mileszs/ack.vim.git
    - https://github.com/scrooloose/nerdcommenter.git
    - https://github.com/scrooloose/nerdtree.git
    - https://github.com/scrooloose/syntastic.git
    - https://github.com/sheerun/vim-polyglot.git
    - https://github.com/tmhedberg/matchit.git
    - https://github.com/tomtom/tlib_vim.git
    - https://github.com/tpope/vim-fugitive.git
    - https://github.com/vim-airline/vim-airline.git
    - https://github.com/vim-airline/vim-airline-themes.git
    - https://github.com/vim-php/tagbar-phpctags.vim.git
    - https://github.com/vim-scripts/CSApprox.git
    - https://github.com/vim-scripts/jQuery.git
    - https://github.com/xolox/vim-misc.git
    - https://github.com/Xuyuanp/nerdtree-git-plugin.git

desktop:
  tools:
    - terminator
    - hexchat
