---
- name: Copy dotfiles
  copy: src={{ item }} dest={{ ansible_user_dir }}/.{{ item | basename }}
  with_fileglob:
    - ./dotfiles/*
  tags:
    - files

- name: Ensure bin/ folder exists
  file: path={{ ansible_user_dir}}/bin state=directory
  tags:
    - files

- name: Copy bin/ files
  copy: src={{ item }} dest={{ ansible_user_dir }}/bin/{{ item | basename }}
  with_fileglob:
    - ./bin/*
  tags:
    - files

- name: Install useful tools (Fedora)
  sudo: yes
  dnf: name={{ item }} state=present
  with_items: "{{ dotfiles.dependencies }}"
  when: ansible_distribution == "Fedora"
  tags:
    - packages
    - network

- name: Install useful tools (Red Hat)
  sudo: yes
  dnf: name={{ item }} state=present
  with_items: "{{ dotfiles.dependencies }}"
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
  tags:
    - packages
    - network

