vim:
  folders:
    - .vim
    - .vim/autoload
    - .vim/bundle
    - .vim/sessions
    - .vim/undodir

  dependencies:
    - vim-enhanced
    - ctags
    - git

  plugins:
    - https://github.com/flazz/vim-colorschemes.git
