---
- name: Install git and tools (Fedora)
  become: yes
  dnf: name={{ item }} state=present
  with_items: "{{ git.dependencies }}"
  when: ansible_distribution == "Fedora"
  tags:
    - packages
    - network

- name: Install git and tools (Red Hat)
  become: yes
  dnf: name={{ item }} state=present
  with_items: "{{ git.dependencies }}"
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
  tags:
    - packages
    - network

- name: Copy dotfiles
  copy: src={{ item }} dest={{ ansible_user_dir }}/.{{ item | basename }}
  with_fileglob:
    - ./dotfiles/*
  tags:
    - files

- name: Create .gitconfig file
  template:  src=gitconfig.j2 dest={{ ansible_user_dir}}/.gitconfig
  tags:
    - files
